### ISSUE TITLE
compile error with boost_1.71

### ISSUE THREAD

**Issue by crnt** [redboltz/mqtt_cpp#554]
[  1%] Building CXX object test/CMakeFiles/as_buffer_pubsub.dir/as_buffer_pubsub.cpp.o
In file included from /home/compiler/working/gateway/mqtt_cpp/include/mqtt/remaining_length.hpp:12:0,
                 from /home/compiler/working/gateway/mqtt_cpp/include/mqtt/endpoint.hpp:39,
                 from /home/compiler/working/gateway/mqtt_cpp/include/mqtt/client.hpp:33,
                 from /home/compiler/working/gateway/mqtt_cpp/test/test_settings.hpp:16,
                 from /home/compiler/working/gateway/mqtt_cpp/test/combi_test.hpp:13,
                 from /home/compiler/working/gateway/mqtt_cpp/test/as_buffer_pubsub.cpp:8:
/home/compiler/working/gateway/mqtt_cpp/include/mqtt/variable_length.hpp: In instantiation of ‘constexpr std::tuple<long unsigned int, long unsigned int> mqtt::variable_length(const T&) [with T = boost::basic_string_view<char, std::char_traits<char> >]’:
/home/compiler/working/gateway/mqtt_cpp/include/mqtt/remaining_length.hpp:25:33:   required from here
/home/compiler/working/gateway/mqtt_cpp/include/mqtt/variable_length.hpp:49:54: error: converting to ‘std::tuple<long unsigned int, long unsigned int>’ from initializer list would use explicit constructor ‘constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = int; _U2 = int; <template-parameter-2-3> = void; _T1 = long unsigned int; _T2 = long unsigned int]’
         if (mul > 128 * 128 * 128 * 128) return {0, 0};
                                                      ^
/home/compiler/working/gateway/mqtt_cpp/include/mqtt/variable_length.hpp:52:26: error: converting to ‘std::tuple<long unsigned int, long unsigned int>’ from initializer list would use explicit constructor ‘constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = long unsigned int&; _U2 = long unsigned int&; <template-parameter-2-3> = void; _T1 = long unsigned int; _T2 = long unsigned int]’
     return {len, consumed};
                          ^
In file included from /home/compiler/working/gateway/mqtt_cpp/include/mqtt/property_variant.hpp:11:0,
                 from /home/compiler/working/gateway/mqtt_cpp/include/mqtt/will.hpp:16,
                 from /home/compiler/working/gateway/mqtt_cpp/include/mqtt/endpoint.hpp:42,
                 from /home/compiler/working/gateway/mqtt_cpp/include/mqtt/client.hpp:33,
                 from /home/compiler/working/gateway/mqtt_cpp/test/test_settings.hpp:16,
                 from /home/compiler/working/gateway/mqtt_cpp/test/combi_test.hpp:13,
                 from /home/compiler/working/gateway/mqtt_cpp/test/as_buffer_pubsub.cpp:8:
/home/compiler/working/gateway/mqtt_cpp/include/mqtt/property.hpp:159:29: error: enclosing class of constexpr non-static member function ‘const mqtt::buffer& mqtt::v5::property::detail::binary_property::val() const’ is not a literal type
     constexpr buffer const& val() const {
                             ^
/home/compiler/working/gateway/mqtt_cpp/include/mqtt/property.hpp:107:8: note: ‘mqtt::v5::property::detail::binary_property’ is not literal because:
 struct binary_property {
        ^
/home/compiler/working/gateway/mqtt_cpp/include/mqtt/property.hpp:107:8: note:   ‘mqtt::v5::property::detail::binary_property’ has a non-trivial destructor
/home/compiler/working/gateway/mqtt_cpp/include/mqtt/property.hpp:224:27: error: enclosing class of constexpr non-static member function ‘std::size_t mqtt::v5::property::detail::variable_property::val() const’ is not a literal type
     constexpr std::size_t val() const {
                           ^
/home/compiler/working/gateway/mqtt_cpp/include/mqtt/property.hpp:179:8: note: ‘mqtt::v5::property::detail::variable_property’ is not literal because:
 struct variable_property {
        ^
/home/compiler/working/gateway/mqtt_cpp/include/mqtt/property.hpp:179:8: note:   ‘mqtt::v5::property::detail::variable_property’ has a non-trivial destructor
In file included from /home/compiler/working/gateway/mqtt_cpp/include/mqtt/remaining_length.hpp:12:0,
                 from /home/compiler/working/gateway/mqtt_cpp/include/mqtt/endpoint.hpp:39,
                 from /home/compiler/working/gateway/mqtt_cpp/include/mqtt/client.hpp:33,
                 from /home/compiler/working/gateway/mqtt_cpp/test/test_settings.hpp:16,
                 from /home/compiler/working/gateway/mqtt_cpp/test/combi_test.hpp:13,
                 from /home/compiler/working/gateway/mqtt_cpp/test/as_buffer_pubsub.cpp:8:
/home/compiler/working/gateway/mqtt_cpp/include/mqtt/variable_length.hpp: In instantiation of ‘constexpr std::tuple<long unsigned int, long unsigned int> mqtt::variable_length(const T&) [with T = boost::container::static_vector<char, 4ul>]’:

**Comment by jonesmz** [comment]
Which release / branch is this?

**Comment by crnt** [comment]
master branch @jonesmz

**Comment by jonesmz** [comment]
What compiler / operating system?

I compile with Boost 1.71, on Gentoo, with both GCC and Clang regularly, and don't have this problem.

**Comment by jonesmz** [comment]
@crnt ?

**Comment by dsxmachina** [comment]
I don't know if this is related or maybe a different issue:

I had similar compilation errors when i compiled w boost 1.71 under Arch;

They disappeared, when i reordered my includes!

It seems that "mqtt_client_cpp.hpp" should not be included **after** other boost stuff (?)
For me it was <boost/program_options.hpp> which gave the error.

But I don't know if this is a bug in mqtt_cpp or boost; but maybe it helps

**Comment by shantanu1singh** [comment]
@dsxmachina I happened to run into the same problem. Including <boost/program_options.hpp> before the mqtt_client_cpp.hpp header file leads to a build failure. It works if you reorder them. Were you able to figure out why that was?

**Comment by dsxmachina** [comment]
@shantanu1singh No not at all. This could be an error in boost or in the mqtt_cpp.
But it is not only the <boost/program_options.hpp>, which causes this behaviour.
I ran into a similar compile error, if i put <boost/geometry/...> headers above mqtt_client_cpp.hpp,
so as a rule of thumb i would say put all the boost stuff after the mqtt headers ;)

**Comment by shantanu1singh** [comment]
@dsxmachina Ah I see. Sounds good. I'll try and investigate what the problem is if I do find the time but thanks for the workaround!

**Comment by bbbrian94** [comment]
could you help to update the newest solution for where to change what kind of sequence of #including?? I am using 1.71 on ubuntu VM and got the exact same issue? does down grade the boost library from 1.71 to 1.67 work for this as well?

**Comment by jonesmz** [comment]
@redboltz I think this issue can be closed.
